name: Weekly Backtesting

on:
  workflow_dispatch:
  schedule:
    # Every Sunday at 11:30 UTC (30 minutes after daily ETL)
    - cron: "30 11 * * 0"

permissions:
  contents: write

concurrency:
  group: weekly-backtesting
  cancel-in-progress: false

jobs:
  weekly-backtesting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci --ignore-scripts --no-audit --fund=false

      - name: Run Weekly Backtesting
        run: npm run etl:backtesting
        env:
          NODE_ENV: production

      - name: Configure git
        run: |
          git config user.name "ghostgauge-bot"
          git config user.email "bot@ghostgauge.local"

      - name: Commit backtesting results
        run: |
          git add public/data/weekly_backtesting_report.json
          if git diff --cached --quiet; then
            echo "No backtesting changes to commit"
            exit 0
          fi
          git commit -m "chore(backtesting): weekly analysis update [skip ci]"
          git push

      - name: Generate Summary
        run: |
          echo "## 📊 Weekly Backtesting Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Weekly backtesting analysis completed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📈 **Updated Files:**" >> $GITHUB_STEP_SUMMARY
          echo "- \`public/data/weekly_backtesting_report.json\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔄 **Next Run:** Next Sunday at 11:00 UTC" >> $GITHUB_STEP_SUMMARY
